### ISSUE TITLE
Sub-tables defined using both table and dotted keys are flagged as duplicates

### ISSUE THREAD

**Issue by tpoliaw** [EmbarkStudios/toml-span#8]
**Describe the bug**
If a table has some entries defined using `dotted.syntax` and some using `[tables]`, they are flagged as duplicates and fail to parse. This is allowed in the spec (end of the [table](https://toml.io/en/v1.0.0#table) section) as `The [table] form can, however, be used to define sub-tables within tables defined via dotted keys.`

**To Reproduce**
```rust
fn main() {
    let src = r#"
        abc.foo = "one"
        [abc.bar]
        fizz = 1
        buzz = 2
        "#;
    let table = toml_span::parse(src);
    println!("{table:?}");
}
```
<details><summary>Gives the duplicate key error</summary>
<pre>
Err(
    Error {
        kind: DuplicateKey {
            key: "abc",
            first: Span {
                start: 9,
                end: 12,
            },
        },
        span: Span {
            start: 34,
            end: 37,
        },
        line_info: Some(
            (
                2,
                9,
            ),
        ),
    },
)
</pre>
</details>

**Expected behavior**
The above example to be parsed into the equivalent of `{'abc': {'bar': {'fizz': 1, 'buzz': 2}, 'foo': 'one'}}`

**Device:**
 - OS: Linux
 - Version 0.3.0
 - rustc 1.82.0

**Comment by baszalmstra** [comment]
We ran into this issue as well with something like the following TOML:

```toml
[tool.ruff]
lint.extend-select = []
lint.ignore = []
lint.fixable = ["ALL"]
lint.unfixable = []

[tool.ruff.lint.extend-per-file-ignores]
"pymablock/block_diagonalization.py" = []
```

Its a strange syntax but not uncommon in the Python world.

I tried looking at the code to see if I could fix it but I couldn't figure it out yet. 

Help would be very much appreciated!!
